[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 9.0   # Gallardo, Mustang
#size = 14.0 # Spider

[env]
TERM = "xterm-256color"
