[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 9.0                                                    # Gallardo, Mustang (Fedora/Linux): 9.0; Spider (MacOS X): 14.0

[env]
TERM = "xterm-256color"
