[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
#size = 9.0   # Gallardo (Fedora/Linux)
size = 10.0 # Mustang (Fedora/Linux)
#size = 14.0 # Spider (MacOS)
